import { Component } from '@angular/core';

@Component({
  selector: 'app-iconfont-grid',
  templateUrl: './app-iconfont-grid.html',
  styleUrl: './app-iconfont-grid.scss',
  standalone: false
})

export class AppIconfontGrid {
  public icons = [
    { icon: "flaticon-calendar" },
    { icon: "flaticon-clock" },
    { icon: "flaticon-success" },
    { icon: "flaticon-internet" },
    { icon: "flaticon-error" },
    { icon: "flaticon-photo-camera" },
    { icon: "flaticon-plus" },
    { icon: "flaticon-like" },
    { icon: "flaticon-music-player" },
    { icon: "flaticon-user" },
    { icon: "flaticon-file-1" },
    { icon: "flaticon-share" },
    { icon: "flaticon-home" },
    { icon: "flaticon-settings" },
    { icon: "flaticon-users" },
    { icon: "flaticon-origami" },
    { icon: "flaticon-diamond" },
    { icon: "flaticon-home-1" },
    { icon: "flaticon-bell" },
    { icon: "flaticon-menu" },
    { icon: "flaticon-flag" },
    { icon: "flaticon-bookmark" },
    { icon: "flaticon-wifi" },
    { icon: "flaticon-trash" },
    { icon: "flaticon-battery" },
    { icon: "flaticon-folder" },
    { icon: "flaticon-layers" },
    { icon: "flaticon-target" },
    { icon: "flaticon-adjust" },
    { icon: "flaticon-download" },
    { icon: "flaticon-menu-1" },
    { icon: "flaticon-price" },
    { icon: "flaticon-app" },
    { icon: "flaticon-bell-1" },
    { icon: "flaticon-smartphone" },
    { icon: "flaticon-filter" },
    { icon: "flaticon-download-1" },
    { icon: "flaticon-music" },
    { icon: "flaticon-mail" },
    { icon: "flaticon-adjust-1" },
    { icon: "flaticon-radar" },
    { icon: "flaticon-control" },
    { icon: "flaticon-adjust-2" },
    { icon: "flaticon-help" },
    { icon: "flaticon-bookmark-1" },
    { icon: "flaticon-cd" },
    { icon: "flaticon-adjust-3" },
    { icon: "flaticon-speaker" },
    { icon: "flaticon-photo-camera-1" },
    { icon: "flaticon-email" },
    { icon: "flaticon-email-1" },
    { icon: "flaticon-message" },
    { icon: "flaticon-wallet" },
    { icon: "flaticon-man" },
    { icon: "flaticon-user-1" },
    { icon: "flaticon-comment" },
    { icon: "flaticon-comment-1" },
    { icon: "flaticon-pencil" },
    { icon: "flaticon-typography" },
    { icon: "flaticon-focus" },
    { icon: "flaticon-idea" },
    { icon: "flaticon-folder-2" },
    { icon: "flaticon-magnifying-glass" },
    { icon: "flaticon-zip-format" },
    { icon: "flaticon-folder-3" },
    { icon: "flaticon-pins" },
    { icon: "flaticon-pins-1" },
    { icon: "flaticon-checked" },
    { icon: "flaticon-list" },
    { icon: "flaticon-file-2" },
    { icon: "flaticon-notes" },
    { icon: "flaticon-trash-1" },
    { icon: "flaticon-layout" },
    { icon: "flaticon-ui" },
    { icon: "flaticon-adjust-4" },
    { icon: "flaticon-tap" },
    { icon: "flaticon-diploma" },
    { icon: "flaticon-safe" },
    { icon: "flaticon-key" },
    { icon: "flaticon-piggy-bank" },
    { icon: "flaticon-coin" },
    { icon: "flaticon-startup" },
    { icon: "flaticon-lock" },
    { icon: "flaticon-locked" },
    { icon: "flaticon-unlocked" },
    { icon: "flaticon-disk" },
    { icon: "flaticon-mouse-1" },
    { icon: "flaticon-mouse" },
    { icon: "flaticon-customer-support" },
    { icon: "flaticon-telemarketer" },
    { icon: "flaticon-language" },
    { icon: "flaticon-coding" },
    { icon: "flaticon-roundabout" },
    { icon: "flaticon-add" },
    { icon: "flaticon-sound" },
    { icon: "flaticon-fullscreen" },
    { icon: "flaticon-eye" },
    { icon: "flaticon-up-arrow" },
    { icon: "flaticon-right-arrow" },
    { icon: "flaticon-key-1" },
    { icon: "flaticon-data" },
    { icon: "flaticon-stop" },
    { icon: "flaticon-search" },
    { icon: "flaticon-star" },
    { icon: "flaticon-harddisk" },
    { icon: "flaticon-globe" },
    { icon: "flaticon-harddisk-1" },
    { icon: "flaticon-notification" },
    { icon: "flaticon-fingerprint" },
    { icon: "flaticon-code" },
    { icon: "flaticon-adjust-5" },
    { icon: "flaticon-inbox" },
    { icon: "flaticon-comment-2" },
    { icon: "flaticon-mobile-camera" },
    { icon: "flaticon-foreground" },
    { icon: "flaticon-square" },
    { icon: "flaticon-pencil-1" },
    { icon: "flaticon-server" },
    { icon: "flaticon-pen" },
    { icon: "flaticon-server-1" },
    { icon: "flaticon-keypad" },
    { icon: "flaticon-monitor" },
    { icon: "flaticon-user-2" },
    { icon: "flaticon-inbox-1" },
    { icon: "flaticon-list-1" },
    { icon: "flaticon-ebook" },
    { icon: "flaticon-calendar-1" },
    { icon: "flaticon-files-and-folders" },
    { icon: "flaticon-repeat" },
    { icon: "flaticon-upload" },
    { icon: "flaticon-curved-arrow" },
    { icon: "flaticon-document" },
    { icon: "flaticon-oval" },
    { icon: "flaticon-storage" },
    { icon: "flaticon-worldwide" },
    { icon: "flaticon-files-and-folders-1" },
    { icon: "flaticon-tray" },
    { icon: "flaticon-cloud" },
    { icon: "flaticon-sun" },
    { icon: "flaticon-cloudy" },
    { icon: "flaticon-umbrella" },
    { icon: "flaticon-wind-socket" },
    { icon: "flaticon-rainy" },
    { icon: "flaticon-rainy-1" },
    { icon: "flaticon-snowflake" },
    { icon: "flaticon-umbrella-1" },
    { icon: "flaticon-wind" },
    { icon: "flaticon-tornado" },
    { icon: "flaticon-cold" },
    { icon: "flaticon-calendar-2" },
    { icon: "flaticon-calendar-3" },
    { icon: "flaticon-focus-1" },
    { icon: "flaticon-user-3" },
    { icon: "flaticon-database" },
    { icon: "flaticon-jigsaw" },
    { icon: "flaticon-gallery" },
    { icon: "flaticon-file" },
    { icon: "flaticon-calculator" },
    { icon: "flaticon-calculator-1" },
    { icon: "flaticon-alarm-clock" },
    { icon: "flaticon-network" },
    { icon: "flaticon-price-tag" },
    { icon: "flaticon-light-bulb" },
    { icon: "flaticon-pantone" },
    { icon: "flaticon-roller" },
    { icon: "flaticon-manufacturing" },
    { icon: "flaticon-lock-1" },
    { icon: "flaticon-compass" },
    { icon: "flaticon-block" },
    { icon: "flaticon-dotted-line" },
    { icon: "flaticon-clip" },
    { icon: "flaticon-yard" },
    { icon: "flaticon-cone" },
    { icon: "flaticon-cut" },
    { icon: "flaticon-sent" },
    { icon: "flaticon-brush" },
    { icon: "flaticon-screw" },
    { icon: "flaticon-stamp" },
    { icon: "flaticon-money" },
    { icon: "flaticon-home-2" },
    { icon: "flaticon-tea-cup" },
    { icon: "flaticon-coffee-cup-1" },
    { icon: "flaticon-coffee-cup" },
    { icon: "flaticon-key-2" },
    { icon: "flaticon-server-2" },
    { icon: "flaticon-add-to-basket" },
    { icon: "flaticon-application" },
    { icon: "flaticon-credit-card" },
    { icon: "flaticon-picture" },
    { icon: "flaticon-crop" },
    { icon: "flaticon-crop-1" },
    { icon: "flaticon-email-2" },
    { icon: "flaticon-message-1" },
    { icon: "flaticon-comment-3" },
    { icon: "flaticon-comment-4" },
    { icon: "flaticon-voice-message" },
    { icon: "flaticon-whatsapp" },
    { icon: "flaticon-mail-1" },
    { icon: "flaticon-comment-5" },
    { icon: "flaticon-selfie" },
    { icon: "flaticon-cartridge" },
    { icon: "flaticon-shutter" },
    { icon: "flaticon-viewfinder" },
    { icon: "flaticon-video-player" },
    { icon: "flaticon-hd" },
    { icon: "flaticon-diskette" },
    { icon: "flaticon-video-player-1" },
    { icon: "flaticon-download-2" },
    { icon: "flaticon-upload-1" },
    { icon: "flaticon-pen-1" },
    { icon: "flaticon-target-1" },
    { icon: "flaticon-target-2" },
    { icon: "flaticon-development" },
    { icon: "flaticon-gearshift" },
    { icon: "flaticon-folder-1" },
    { icon: "flaticon-internet-1" },
    { icon: "flaticon-heart" },
    { icon: "flaticon-left-arrow" },
    { icon: "flaticon-right-arrow-1" },
    { icon: "flaticon-up-arrow-1" },
    { icon: "flaticon-memory-card" },
    { icon: "flaticon-streaming" },
    { icon: "flaticon-arrows" },
    { icon: "flaticon-down-arrow" },
    { icon: "flaticon-signal" },
    { icon: "flaticon-orientation" },
    { icon: "flaticon-bass" },
    { icon: "flaticon-diagonal" },
    { icon: "flaticon-playlist" },
    { icon: "flaticon-diagonal-1" },
    { icon: "flaticon-usb" },
    { icon: "flaticon-alert" },
    { icon: "flaticon-expand" },
    { icon: "flaticon-id-card" },
    { icon: "flaticon-smartwatch-1" },
    { icon: "flaticon-charger" },
    { icon: "flaticon-apps" },
    { icon: "flaticon-smartwatch" },
    { icon: "flaticon-batteries" },
    { icon: "flaticon-socket" },
  ]

  /**
   * Copia el icono seleccionado al portapapeles
   *
   * @param {string} text  - Texto original del icono
   * @author Carlos Salas
   * 29/Jan/2026
   */
  public copyToClipboard(text: string): void {
    const completeText: string = "<span class='" + text + "'></span>";
    navigator.clipboard.writeText(completeText)
      .then(() => {
        console.log("Texto copiado correctamente ✅");
      })
      .catch(err => {
        console.error("Error al copiar ❌", err);
      });
  }
}
